server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    access_log off;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "DENY" always;
    add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; img-src 'self' data:; font-src 'self'; script-src 'self'; style-src 'self'; connect-src 'none'" always;
    add_header Cache-Control "no-cache" always;

    error_page 404 /404.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
